version: '3.1'

services:

  appcomms:
    image: ppeluffo/apicomms:latest
    ports:
      - 5000:5000
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.20:514"
        tag: "APICOMMS" 
        
  apiredis:
    image: ppeluffo/apiredis:latest
    ports:
      - 5100:5100
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.20:514"
        tag: "APICOMMS" 

  apiconf:
    image: ppeluffo/apiconf:latest
    ports:
      - 5200:5200
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.20:514"
        tag: "APICOMMS"

  redis:
    image: redis:alpine

  pgsql:
    image: ppeluffo/bd_apicomms:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pexco599
      POSTGRES_DB: bd_unidades
    volumes:
      - /datos:/var/lib/postgresql/data


