version: '3.1'

services:

  apicomms:
    build:
      context: ./apicomms
      dockerfile: Dockerfile
    image: spymovil/commsv3_apicomms:latest
    ports:
      - 5000:5000
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.20:514"
        tag: "APICOMMS" 
    depends_on:
      - apiredis
      - apiconf
    environment:
      APIREDIS_HOST: apiredis
      APIREDIS_PORT: 5100
      APICONF_HOST: apiconf
      APICONF_PORT: 5200

  apiconf:
    build:
      context: ./apiconf
      dockerfile: Dockerfile
    image: spymovil/commsv3_apiconf:latest
    ports:
      - 5200:5200
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.9:514"
        tag: "APICOMMS"
    depends_on:
      - pgsql
    environment:
      PGSQL_HOST: pgsql
      PGSQL_PORT: 5432
      PGSQL_USER: admin
      PGSQL_PASSWD: pexco599
      PGSQL_BD: bd_spcomms

  apidatos:
    build:
      context: ./apidatos
      dockerfile: Dockerfile
    image: spymovil/commsv3_apidatos:latest
    ports:
      - 5300:5300
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.9:514"
        tag: "APICOMMS"
    depends_on:
      - pgsql
    environment:
      PGSQL_HOST: pgsql
      PGSQL_PORT: 5432
      PGSQL_USER: admin
      PGSQL_PASSWD: pexco599
      PGSQL_BD: bd_spcomms
      APIDATOS_HOST: apidatos
      APIDATOS_PORT: 5300
      MAX_SELECT_CHUNK_SIZE: 100

  apiredis:
    build:
      context: ./apiredis
      dockerfile: Dockerfile
    image: spymovil/commsv3_apiredis:latest
    ports:
      - 5100:5100
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.9:514"
        tag: "APICOMMS" 
    depends_on:
      - redis
    environment:
      BDREDIS_HOST: redis
      BDREDIS_PORT: 6379
      BDREDIS_DB: 0

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /datos_redis:/data

  pgsql:
    build:
      context: ./pgsql
      dockerfile: Dockerfile
    image: spymovil/commsv3_pgsql:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pexco599
      POSTGRES_DB: bd_spcomms
    volumes:
      - /datos:/var/lib/postgresql/data

  process:
    build:
      context: ./process
      dockerfile: Dockerfile
    image: spymovil/commsv3_process:latest
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://192.168.0.9:514"
        tag: "APICOMMS"
    depends_on:
      - pgsql
      - redis
    environment:
      APIREDIS_HOST: apiredis
      APIREDIS_PORT: 5100
      PGSQL_HOST: pgsql
      PGSQL_PORT: 5432
      PGSQL_USER: admin
      PGSQL_PASSWD: pexco599
      PGSQL_BD: bd_spcomms
      MAX_INSERTS_CHUNK_SIZE: 100
      MAX_DEQUEUE_ITEMS: 100
      SLEEP_TIME: 60
      


