-- Table: public.configuraciones

-- DROP TABLE IF EXISTS public.tb_configuraciones;

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_id VARCHAR (30), 
    fechaUltimoAcceso timestamp(0) without time zone NOT NULL,
    data_ptr bigint
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuarios
    OWNER to admin;
    