-- Table: public.historica

-- DROP TABLE IF EXISTS public.historica;

CREATE TABLE IF NOT EXISTS public.historica
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fechadata timestamp(0) without time zone NOT NULL,
    fechasys timestamp(0) without time zone NOT NULL,
    equipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tag character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(20,6) NOT NULL,
    CONSTRAINT historica_fechadata_equipo_tag_1cef2062_uniq UNIQUE (fechadata, equipo, tag)
)

TABLESPACE pg_default;

SELECT create_hypertable('public.historica', 'fechadata', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);

ALTER TABLE IF EXISTS public.historica
    OWNER to admin;
-- Index: historica_idx

-- DROP INDEX IF EXISTS public.historica_idx;

CREATE INDEX IF NOT EXISTS historica_idx
    ON public.historica USING btree
    (fechadata ASC NULLS LAST, equipo COLLATE pg_catalog."default" ASC NULLS LAST, tag COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: historica_timestamp_idx

-- DROP INDEX IF EXISTS public.historica_timestamp_idx;

CREATE INDEX IF NOT EXISTS historica_timestamp_idx
    ON public.historica USING btree
    (fechadata DESC NULLS FIRST)
    TABLESPACE pg_default;