-- Table: public.online

-- DROP TABLE IF EXISTS public.online;

CREATE TABLE IF NOT EXISTS public.online
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fechadata timestamp(0) without time zone NOT NULL,
    fechasys timestamp(0) without time zone NOT NULL,
    equipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tag character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valor double precision NOT NULL,
    CONSTRAINT online_fechadata_equipo_tag_1cef2062_uniq UNIQUE (fechadata, equipo, tag)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.online
    OWNER to admin;
-- Index: online_idx

-- DROP INDEX IF EXISTS public.online_idx;

CREATE INDEX IF NOT EXISTS online_idx
    ON public.online USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: online_timestamp_idx

CREATE INDEX IF NOT EXISTS datos_fecha_idx
    ON public.online USING btree
    (fechadata ASC NULLS LAST, equipo COLLATE pg_catalog."default" ASC NULLS LAST, tag COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: online_timestamp_idx

-- DROP INDEX IF EXISTS public.online_timestamp_idx;

CREATE INDEX IF NOT EXISTS online_timestamp_idx
    ON public.online USING btree
    (fechadata DESC NULLS FIRST)
    TABLESPACE pg_default;
